bars:
  yasb_bar:                   # Required, label MUST be in snake_case or ClassCase e.g. "foo_bar" or "FooBar"
    thickness: 84             # Optional, default: 64, the width (or height) of the bar in pixels
    edge: "top"               # Optional, default: top, options: top|left|bottom|right
    screens: []               # Optional, default: [] (all screens), takes: list of screen names to show bar on
    win_app_bar: false        # Optional, default: false, registers bar as a Windows Application Desktop Toolbar (e.g. a custom taskbar)
    always_on_top: true       # Optional, default: false, ensures bar is always at TOPMOST window level
    widgets:                  # Provide a list of widgets for left, middle and right bar columns
      left: [ left_txt ]
      middle: [ center_txt ]
      right: [ right_txt, sep, DateTimeWidget ]

widgets:
  left_txt:
    kind: TextWidget
    text: "left"
  
  right_txt:
    kind: TextWidget
    text: "right"
  
  center_txt:
    kind: TextWidget
    text: "middle"

  sep:
    kind: TextWidget
    text: "|"
    class: separator