name: Build .msi

on:
  push:
    branches: [ "tauri-port" ]
  pull_request:
    branches: [ "tauri-port" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: node -v
    - run: npm install
    - run: npm run tauri build
    - run: ls ./src-tauri/target/release/bundle/msi
